services:
  mariadb_row:
    image: mariadb:latest
    environment:
      MYSQL_ROOT_PASSWORD: 1
      MYSQL_USER: test_db
      MYSQL_PASSWORD: test_db
      MYSQL_DATABASE: flights_row
    ports:
      - "3307:3307"
    volumes:
      - ./mariadb-data:/var/lib/mysql
  mariadb_column:
    image: mariadb/columnstore:latest
    environment:
      MYSQL_ROOT_PASSWORD: 1
      MYSQL_USER: test_db
      MYSQL_PASSWORD: test_db
      MYSQL_DATABASE: flights_column
    ports:
      - "3308:3308"
    volumes:
      - ./mariadb-data:/var/lib/mysql
